export const defaultGenres = [
  { value: "random", label: "Random" },
  { value: "hiphop", label: "Hip-hop" },
  { value: "pop", label: "Pop" },
];
export const defaultMoods = [
  { value: "chill", label: "Chill" },
  { value: "sentimental", label: "Sentimental" },
];
export const defaultNumPlays = [
  { value: "fresh", label: "Fresh Finds (< 100,000 plays)" },
  { value: "indie", label: "Indie Mix (< 5,000,000 plays)" },
  { value: "pop", label: "Popular Music (> 50,000,000 plays)" },
];

export const moodValues = {
  chill: {
    target_acousticness: 0.8,
    target_danceability: 0.2,
    // ...
  },
};

// API call constants
export const SPOTIFY = "https://accounts.spotify.com/api/token";
export const ARTIST =
  "https://api.spotify.com/v1/recommendations/available-genre-seeds";
export const RECOMMENDATION = "https://api.spotify.com/v1/recommendations";

// Genre Constants
export const genreSeeds = [
  "acoustic",
  "afrobeat",
  "alt-rock",
  "alternative",
  "ambient",
  "anime",
  "black-metal",
  "bluegrass",
  "blues",
  "bossanova",
  "brazil",
  "breakbeat",
  "british",
  "cantopop",
  "chicago-house",
  "children",
  "chill",
  "classical",
  "club",
  "comedy",
  "country",
  "dance",
  "dancehall",
  "death-metal",
  "deep-house",
  "detroit-techno",
  "disco",
  "disney",
  "drum-and-bass",
  "dub",
  "dubstep",
  "edm",
  "electro",
  "electronic",
  "emo",
  "folk",
  "forro",
  "french",
  "funk",
  "garage",
  "german",
  "gospel",
  "goth",
  "grindcore",
  "groove",
  "grunge",
  "guitar",
  "happy",
  "hard-rock",
  "hardcore",
  "hardstyle",
  "heavy-metal",
  "hip-hop",
  "holidays",
  "honky-tonk",
  "house",
  "idm",
  "indian",
  "indie",
  "indie-pop",
  "industrial",
  "iranian",
  "j-dance",
  "j-idol",
  "j-pop",
  "j-rock",
  "jazz",
  "k-pop",
  "kids",
  "latin",
  "latino",
  "malay",
  "mandopop",
  "metal",
  "metal-misc",
  "metalcore",
  "minimal-techno",
  "movies",
  "mpb",
  "new-age",
  "new-release",
  "opera",
  "pagode",
  "party",
  "philippines-opm",
  "piano",
  "pop",
  "pop-film",
  "post-dubstep",
  "power-pop",
  "progressive-house",
  "psych-rock",
  "punk",
  "punk-rock",
  "r-n-b",
  "rainy-day",
  "reggae",
  "reggaeton",
  "road-trip",
  "rock",
  "rock-n-roll",
  "rockabilly",
  "romance",
  "sad",
  "salsa",
  "samba",
  "sertanejo",
  "show-tunes",
  "singer-songwriter",
  "ska",
  "sleep",
  "songwriter",
  "soul",
  "soundtracks",
  "spanish",
  "study",
  "summer",
  "swedish",
  "synth-pop",
  "tango",
  "techno",
  "trance",
  "trip-hop",
  "turkish",
  "work-out",
  "world-music",
];

// Vibe Constants
export const vibeSeeds = [
  {
    value: "energetic",
    label: "Energetic",
    acousticness: 0,
    danceability: 1,
    energy: 1,
    loudness: 1,
  },
  {
    value: "joyful",
    label: "Joyful",
    acousticness: 0.1,
    danceability: 0.9,
    energy: 0.8,
    loudness: 0.7,
  },
  {
    value: "daily",
    label: "Daily",
    acousticness: 0.2,
    danceability: 0.6,
    energy: 0.7,
    loudness: 0.6,
  },
  {
    value: "chill",
    label: "Chill",
    acousticness: 0.5,
    danceability: 0.5,
    energy: 0.5,
    loudness: 0.5,
  },
  {
    value: "relax",
    label: "Relax",
    acousticness: 1,
    danceability: 0,
    energy: 0,
    loudness: 0.1,
  },
];
